name: Status

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        ruby: [ '2.6.0' ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby version
      uses: actions/setup-ruby@master
      with:
        version: ${{ matrix.ruby }}

    - name: Set up bundler
      run: gem install bundler

    - name: bundle install
      run: bundle install --jobs 4 --retry 3

    - name: test
      run: bundle exec rspec
